// <auto-generated />
using System;
using Backend.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240731012314_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Caminhao", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<decimal>("CapacidadeDeCarga")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CodigoVeiculo")
                        .HasColumnType("int");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoVeiculo")
                        .IsUnique();

                    b.ToTable("Caminhao");
                });

            modelBuilder.Entity("Backend.Models.Carro", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<int>("CapacidadePassageiro")
                        .HasColumnType("int");

                    b.Property<int>("CodigoVeiculo")
                        .HasColumnType("int");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoVeiculo")
                        .IsUnique();

                    b.ToTable("Carro");
                });

            modelBuilder.Entity("Backend.Models.Revisao", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<int>("CodigoVeiculo")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataRevisao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quilometragem")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorRevisao")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoVeiculo");

                    b.ToTable("Revisao");
                });

            modelBuilder.Entity("Backend.Models.Veiculo", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoVeiculo")
                        .HasColumnType("int");

                    b.HasKey("Codigo");

                    b.ToTable("Veiculo");
                });

            modelBuilder.Entity("Backend.Models.Caminhao", b =>
                {
                    b.HasOne("Backend.Models.Veiculo", "Veiculo")
                        .WithOne("Caminhao")
                        .HasForeignKey("Backend.Models.Caminhao", "CodigoVeiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Backend.Models.Carro", b =>
                {
                    b.HasOne("Backend.Models.Veiculo", "Veiculo")
                        .WithOne("Carro")
                        .HasForeignKey("Backend.Models.Carro", "CodigoVeiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Backend.Models.Revisao", b =>
                {
                    b.HasOne("Backend.Models.Veiculo", "Veiculo")
                        .WithMany("Revisoes")
                        .HasForeignKey("CodigoVeiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Backend.Models.Veiculo", b =>
                {
                    b.Navigation("Caminhao");

                    b.Navigation("Carro");

                    b.Navigation("Revisoes");
                });
#pragma warning restore 612, 618
        }
    }
}
